---
tags: ["Code-Generation","defect","help-wanted"]
title: "Crash when bounds of prange() are Python objects"
html_url: "https://github.com/cython/cython/issues/2504"
user: "scoder"
repo: "cython/cython"
---

