---
tags: ["Bug","data-analysis","data-science","machine-learning","python","statistics"]
title: "`ValueError` raised by `FeatureUnion._set_output` with `FunctionTransform` that outputs a pandas `Series` in scikit-learn version 1.6"
html_url: "https://github.com/scikit-learn/scikit-learn/issues/31318"
user: "Bilalbrahimi"
repo: "scikit-learn/scikit-learn"
---

